version: "3.9"

services:
  db:
    container_name: db
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Lavka
    ports:
      - "5432:5432"
    restart: always