version: "3.9"

services:
  service:
    container_name: lavka
    build:
      dockerfile: Dockerfile
    environment:
      - STORAGE_URL="postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always